#' Sigmoid
#'
#' The sigmoid function is used to determine a 'y' value for any given 'x'.
#'
#' @param b value of the slope at the inflection point
#' @param c lower asymptote value
#' @param d higher asymptote
#' @param e xmid
#' @param f
#' @param x_new can be a list or a single value used to determine 'y'
#'
#' @return A 'y' value or list of 'y' values generated by the sigmoid function
#' @export
#'
sigmoid_drm_BC <- function (b, c, d, e, f, x_new){
  y = c + ((d - c + f*(x_new))/ (1 + exp(b*(log(x_new) - log(e)))))
  return(y)
}
